UWprj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("uwapp.urls")),
    path("user/",include("userauth.urls")),

    path("ckeditor/",include("ckeditor_uploader.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

userauth/urls.py
from django.urls import path
from userauth import views

app_name= "userauth"

urlpatterns = [
    path("signup/", views.signup,name="signup"),
    path("login/", views.signin,name="login"),
    path("logout/", views.signout,name="signout"),
]

uwapp/urls.py
from django.urls import path,include
from uwapp.views import payment_completed,payment_failed,product,login_required,cart,category,category_product,checkout,delete_item_from_cart,details,index,account,add_to_cart,orders

app_name="uwapp"

urlpatterns = [
    path("",index,name="index"),

    path("product/",product,name="product"),

    path("category/<cid>",category_product,name="category_product"),

    path("category/",category,name="category"),

    path("details/<Pid>/",details,name="details"),

    path("add_to_cart/",add_to_cart,name="add_to_cart"),

    path("cart/",cart,name="cart"),

    path("delete-from-cart/",delete_item_from_cart,name="delete-from-cart"),

    path("account/",account,name="account"),

    path("orders/",orders,name="orders"),
    
    path("checkout/",checkout,name="checkout"),


    path('payment/success/', payment_completed, name='payment_success'),
    
    path('payment/failed/', payment_failed, name='payment_failed'),

]

uwapp/models.py
from django.db import models
from shortuuid.django_fields import ShortUUIDField
from django.utils.html import mark_safe
from userauth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.translation import gettext_lazy as _
from django.db.models.fields import CharField

# Create your models here.

STATUS_CHOICE=(("processing","Processing"),("shipped","Shipped"),("delivered","Delivered"), )

STATUS=(("draft","Draft"),("disabled","Disabled"),("rejected","Rejected"),("published","published"))

def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.user.id,filename)

class Category(models.Model):
    cid = ShortUUIDField(unique=True, length=10, max_length=30, prefix="cat",alphabet="abcdefghijklm12345")
    name = models.CharField(max_length=100,default="cloth") 
    image = models.ImageField(upload_to="category")

    class Meta:
        verbose_name_plural = "categories"

    def category_image(self):
        return mark_safe('<img src="%s" width="50" height="50"/>' % (self.image.url))
    
    def __str__(self) :
        return self.name
    
class Product(models.Model):
    Pid = ShortUUIDField(unique=True, length=10, max_length=30, prefix="prd",alphabet="abcdefghijklm12345")    
    user = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    name = models.CharField(max_length=100) 
    image = models.ImageField(upload_to=user_directory_path)
    description = RichTextUploadingField(null=True,blank=True,default="This is the product")
    category=models.ForeignKey(Category,on_delete=models.SET_NULL,null=True,related_name="category")
    price= models.DecimalField(max_digits=99999,decimal_places=2,default="300.00")
    product_status =  models.CharField(choices=STATUS,max_length=10,default="in_review")
    featured = models.BooleanField(default=True)
    small_in_stock = models.BooleanField(default=True)
    medium_in_stock = models.BooleanField(default=True)
    large_in_stock = models.BooleanField(default=True)
    xl_in_stock = models.BooleanField(default=True)
    date = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(null=True,blank=True)

    class Meta:
        verbose_name_plural = "Product"

    def product_image(self):
        return mark_safe('<img src="%s" width="50" height="50"/>' % (self.image.url))
    
    def __str__(self) :
        return self.name    
    
class productimage(models.Model):
    images = models.ImageField (upload_to="product-image")
    product = models.ForeignKey(Product,related_name="p_images",on_delete=models.SET_NULL,null=True)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "productimages"

######################################################################## cartorder #######################################################################################
######################################################################## cartitems ####################################################################################### 
 
class CartOrder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    mail=models.EmailField(default="")
    price= models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    Address = models.TextField(max_length=100,default="")
    Phone = models.CharField(max_length=20,default="Number")
    paid_status = models.BooleanField(default=False)
    order_date = models.DateTimeField(auto_now_add=True)
    product_status =  models.CharField(choices=STATUS_CHOICE,max_length=30,default="processing")
    order_identifier = models.CharField(max_length=40,default="",null=True)
    razorpay_payment_id = models.CharField(max_length=40,default="",null=True)
    razorpay_signature = models.CharField(max_length=100,default="",null=True)

    
    class Meta:
        verbose_name_plural = "cart order"

class CartOrderItems(models.Model):
    order = models.ForeignKey(CartOrder, on_delete=models.CASCADE)
    order_identifier = models.CharField(max_length=40,default="",null=True)
    invoice_no =  models.CharField(max_length=200,default="")
    item =  models.CharField(max_length=200)
    image =  models.CharField(max_length=200)
    qty = models.IntegerField(default=0)
    price= models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    total= models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    size = models.CharField(max_length=10,default='N/A')
    
    class Meta:
        verbose_name_plural = "cart order items"

    def category_image(self):
        return mark_safe('<img src="%s" width="50" height="50"/>' % (self.image.url))
    
    def order_image(self):
        return mark_safe('<img src="/media/%s" width="50" height="50"/>' % (self.image))
    
######################################################################## Address #####################################################################################

class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    Address = models.CharField(max_length=200,null=True)
    phone_num = models.CharField(max_length=15, null=True)

    class Meta:
        verbose_name_plural = "Address"






    
    

uwapp/views.py
from django.shortcuts import render , redirect
from uwapp.models import CartOrder, CartOrderItems, Category, productimage, Product, Address
from userauth.models import User
from django.http import JsonResponse
from django.contrib import messages
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.utils import timezone
import razorpay
from django.core.mail import send_mail
from django.http import HttpResponseBadRequest
from django.contrib import messages

def index(request): 
    products= Product.objects.filter(featured=True,product_status="published")
    context = {
        "products":products
    }
    if request.method == 'POST':
        name = request.POST.get('name', '') 
        review_text = request.POST.get('review_text', '')  
        email = request.POST.get('email', '') 
        subject = 'New Review Submitted'
        message = f'Name: {name}\nReview: {review_text}'
        from_email = {email}  
        recipient_list = ['sidhupkc@gmail.com']  
        send_mail(subject, message, from_email, recipient_list)
        messages.info(request, 'sent ! Thank you for your Review')
        return redirect('uwapp:index')

        
    return render(request,'uwapp/index.html',context)

def product(request):
    product = Product.objects.filter(product_status="published")
    context = {
        "products":product
    }
    return render(request,'uwapp/product.html',context)

def category(request):
    categories = Category.objects.all()  
    context = {
        "categories":categories
    }
    return render(request,'uwapp/category.html',context)

def category_product(request, cid):
    category = Category.objects.get(cid=cid)
    product = Product.objects.filter(product_status="published",category=category)
    context = {
        "category":category,
        "product":product
    }
    return render(request ,'uwapp/category-product.html',context )

def details(request,Pid , ): 
    product = Product.objects.get(Pid=Pid)
    p_image= product.p_images.all()
    context={
        "p":product,
        "p_image":p_image,

    }
    return render(request,'uwapp/productpage.html',context)

@login_required
def account(request):
    account = request.user
    existing_address = Address.objects.filter(user=request.user).first()
    existing_phone = existing_address.phone_num if existing_address else None
    
    if request.method == "POST":
        new_address_text = request.POST.get("address")
        new_phone_text = request.POST.get("phone")
        if existing_address:
            existing_address.Address = new_address_text
            existing_address.phone_num = new_phone_text
            existing_address.save()
        else:
            existing_address = Address(user=request.user, Address=new_address_text, phone_num=new_phone_text)
            existing_address.save()

    # You should refresh the existing_address after the update.
    existing_address = Address.objects.filter(user=request.user).first()

    context = {
        "account": account,
        "existing_address": existing_address,
        "existing_phone": existing_address.phone_num if existing_address else None,
    }
    return render(request, 'uwapp/account.html', context)


def add_to_cart(request):
    product_id = request.GET.get('id')
    product_name = request.GET.get('name')
    product_qty = request.GET.get('qty')
    product_price = request.GET.get('price')
    product_size = request.GET.get('size')
    product_image = request.GET.get('image')

    if not all([product_id, product_name, product_qty, product_price, product_size]):
        return JsonResponse({"error": "Invalid request parameters"})

    cart_data_obj = request.session.get('cart_data_obj', {})

    # Create a unique identifier for the product based on ID and size
    cart_product_id = f"{product_id}_{product_size}"

    if cart_product_id in cart_data_obj:
        # Product with the same ID and size is already in the cart
        existing_qty = cart_data_obj[cart_product_id]['qty']
        cart_data_obj[cart_product_id]['qty'] = existing_qty + int(product_qty)
    else:
        # Product with the given ID and size is not in the cart, so add it
        cart_product = {
            'name': product_name,
            'qty': int(product_qty),
            'price': float(product_price),
            'size': product_size,
            'pid': product_id,
            'image': product_image,
        }
        cart_data_obj[cart_product_id] = cart_product

    request.session['cart_data_obj'] = cart_data_obj

    response_data = {
        "data": request.session['cart_data_obj'],
        'totalcartitems': len(request.session['cart_data_obj']),
    }
    return JsonResponse(response_data)

    

def cart(request):
    cart_total_amount = 0
    cart_data_obj = request.session.get('cart_data_obj', {})  
    if cart_data_obj:
        for p_id, item in cart_data_obj.items():
            qty = int(item['qty'])
            price = float(item['price'])
            cart_total_amount += qty * price
            
        return render(request, 'uwapp/cart.html', {
            "cart_data": cart_data_obj,
            'totalcartitems': len(cart_data_obj),
            'cart_total_amount': cart_total_amount
        })
    else:
        messages.warning(request, "Your cart is empty")
        return redirect('uwapp:index')
    
def delete_item_from_cart(request):
    product_id = str(request.GET.get('id'))  
    if 'cart_data_obj' in request.session:
        cart_data = request.session['cart_data_obj']
        
        if product_id in cart_data:
            del cart_data[product_id]
            request.session['cart_data_obj'] = cart_data  
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            qty = int(item['qty'])
            price = float(item['price'])
            cart_total_amount += qty * price
    context = {
        "cart_data": request.session.get('cart_data_obj', {}), 
        'totalcartitems': len(request.session.get('cart_data_obj', {})),  
        'cart_total_amount': cart_total_amount,
    }
    rendered_html = render_to_string("core/async/cart-list.html", context)
    return JsonResponse({"data": rendered_html, 'totalcartitems': len(request.session.get('cart_data_obj', {}))})

    
def orders(request):
    orders = CartOrder.objects.filter(user=request.user)
    context = {
        "orders":orders,
    }
    return render(request,'uwapp/orders.html',context)



razorpay_client = razorpay.Client(auth=(settings.RAZOR_KEY_ID, settings.RAZOR_KEY_SECRET))
@login_required
def checkout(request):
    cart_total_amount = 0
    total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            qty = int(item['qty'])
            price = float(item['price'])
            total_amount += qty * price
        user = request.user  
        mail = request.user.email

        # user_address = Address.objects.get(user=user)

        try:
            user_address = Address.objects.get(user=user)
        except Address.DoesNotExist:
            # messages.error(request, "No address found. Please update your address in your account before checkout.")
            return redirect("uwapp:account")
        
        user_phone_number = user_address.phone_num if user_address else None
        address=user_address.Address
        Phone=user_address.phone_num if user_address else None,

        order = CartOrder.objects.create(
            user=user,
            price=total_amount,
            mail=mail,
            Address=address,
            Phone=user_address.phone_num if user_address else None,
            order_identifier=''
        )
        for p_id, item in request.session['cart_data_obj'].items():
            qty = int(item['qty'])
            price = float(item['price'])
            cart_total_amount += qty * price
            cart_order_products = CartOrderItems.objects.create(
                order=order,
                invoice_no="invoice_no-" + str(order.id),
                item=item['name'],
                image=item['image'],
                qty=qty,
                price=price,
                total=qty * price,
                size=item.get('size', ''),
                order_identifier='',
            )
        amount = int(cart_total_amount * 100)
        data = {
            'amount': amount,
            'currency': 'INR',
            'payment_capture': 1,
        }
        razorpay_order = razorpay_client.order.create(data=data)
        razorpay_order_id = razorpay_order['id']
        order.order_identifier = razorpay_order_id
        order.save()
        for cart_order_item in CartOrderItems.objects.filter(order=order):
            cart_order_item.order_identifier = razorpay_order_id
            cart_order_item.save()

        return render(request, 'uwapp/checkout.html', {
            "cart_data": request.session['cart_data_obj'],
            'totalcartitems': len(request.session['cart_data_obj']),
            'cart_total_amount': cart_total_amount,
            'AMOUNT': amount,
            'razorpay_order_id': razorpay_order_id,
            'username': request.user.username,
            'email': request.user.email,
            'id': razorpay_order_id,
            'order': razorpay_order,'phone':user_phone_number,'address':address,
        })
    else:
        return redirect('cart_empty_page')





@csrf_exempt
@login_required
def payment_completed(request):
    if request.method == 'POST':
        try:
            payment_id = request.POST.get('razorpay_payment_id')
            payment_signature = request.POST.get('razorpay_signature')
        except KeyError:

templates/uwapp/account.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

<body>
    <script> AOS.init({ once: true, });</script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
    <!--taskbar-->

    <section class="taskbar ">
        <nav class="menu" data-aos="flip-left" data-aos-duration="2000">
            <a href="{% url 'uwapp:index' %}"><img src="{% static 'img/undrwrld final logo-03.png' %}" alt="">
            </a>
        </nav>
        <nav class="menu_2">
            <a href="{% url 'userauth:login'  %}">Login</a>
            <a href="{% url 'uwapp:cart' %}"><img src="{% static 'img/cart.png' %}" alt=""></a>
            <a href="{% url 'uwapp:account' %}"><img src="{% static 'img/user.png' %}" alt=""></a>
            <!-- Toogle -->

            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbarDark" aria-controls="offcanvasNavbarDark">
                <img src="{% static 'img/menu.png' %}" alt="">
            </button>

            <!--sider-->
            <div class="sidebar offcanvas offcanvas-end text-white" tabindex="-1" id="offcanvasNavbarDark"
                aria-labelledby="offcanvasNavbarDarkLabel">
                <div class="offcanvas-header text-white border-bottom">
                    <h5 class="offcanvas-title" id="offcanvasNavbarDarkLabel">UndrWorld</h5>
                    <button type="button" class="btn-close btn-close-white shadow-none" data-bs-dismiss="offcanvas"
                        aria-label="Close"></button>
                </div>
                <!--SIder body-->
                <div class="offcanvas-body d-flex flex-column p-4">
                    <ul class="navbar-nav justify-content-center align-items-center flex-grow-1 pe-3">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'uwapp:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'uwapp:account' %}">Account</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'uwapp:category' %}">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'uwapp:product' %}">All Products</a>
                        </li>
                    </ul>
                    <!--Log in / Signup-->
                    <div class="d-flex flex-column justify-content-center align-items-center gap-3">
                        <a href="{% url 'userauth:login'  %}">Login</a>
                        <a href="{% url 'userauth:signup' %}" class="btn btn-primary">Signup</a>
                    </div>
                </div>
            </div>
        </nav>
    </section>

    <!--account_content-->

    <section class="account-page">
        <div class="container mt-5">
            <div class="row">
                <div class="col-lg-3">
                    <!-- Sidebar -->
                    <div class="list-group">
                        <a href="#" class="list-group-item list-group-item-action active">My Account</a>
                        <a href="{% url 'uwapp:account' %}" class="list-group-item list-group-item-action">Profile</a>
                        <a href="{% url 'uwapp:orders' %}" class="list-group-item list-group-item-action">Orders</a>
                        <a href="{% url 'userauth:signout' %}" class="list-group-item list-group-item-action">Logout</a>
                    </div>
                </div>
                <div class="col-lg-5">
                    <!-- Content Area -->
                    <h1 class="">Welcome, {{ account.username }}</h1>
                    <div class="card ard">
                        <div class="card-body">
                            <p class="card-text"><strong>Name:</strong> {{ account.username }}</p>
                            <p class="card-text"><strong>Email:</strong> {{ account.email }}</p>
                    
                            {% if existing_phone %}
                                <p class="card-text"><strong>Phone:</strong> {{ existing_phone }}</p>
                            {% else %}
                                <p class="card-text"><strong>Phone:</strong></p>
                            {% endif %}
                    
                            {% if existing_address %}
                                <p class="card-text"><strong>Address:</strong> {{ existing_address.Address }}</p>
                            {% else %}
                                <p class="card-text"><strong>Address:</strong></p>
                            {% endif %}
                            <!-- Add more user details as needed -->
                        </div>
                    </div>
                    
                       
                </div>
                <div class="col-lg-4">
                    <div class="card ard mt-4">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="address">Address</label>
                                    <input type="text" class="form-control" id="address" name="address" placeholder="{{ existing_address.Address }}" required>
                                </div>
                                <div class="form-group mt-2">
                                    <label for="zip">Phone</label>
                                    <input type="tel" class="form-control" id="zip" name="phone" placeholder="{{ existing_phone }}" required>
                                </div>
                                <button type="submit" class="btn btn-primary mt-4" id="saveAddress">Update</button>
                            </form>
                        </div>
                    </div>
            </div>
        </div>
        </main>
    </section>
</body>
<footer class="footer_x ">

    <div class="text-center p-3" style="background-color: white;">
        &copy; 2023 Your Website. All rights reserved.
    </div>
</footer>

</html>
{% endblock content %}

templates/uwapp/orders.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %} 

<body>
    <script>
        AOS.init({ once: true, });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    
    <!--Taskbar-->

    <section class="taskbar ">
        <nav class="menu"  data-aos="flip-left" data-aos-duration="2000">
            <a href="{% url 'uwapp:index' %}"><img src="{% static 'img/undrwrld final logo-03.png' %}" alt="">
            </a>
        </nav>
        <nav class="menu_2">
            <a href="{% url 'userauth:login'  %}">Login</a>
            <a href="{% url 'uwapp:cart' %}"><img src="{% static 'img/cart.png' %}" alt=""></a>
            <a  href="{% url 'uwapp:account' %}"><img src="{% static 'img/user.png' %}" alt=""></a>
            <!-- Toogle -->

            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbarDark" aria-controls="offcanvasNavbarDark">
                <img src="{% static 'img/menu.png' %}" alt="">
            </button>

            <!--sider-->
            <div class="sidebar offcanvas offcanvas-end text-white" tabindex="-1" id="offcanvasNavbarDark"
                aria-labelledby="offcanvasNavbarDarkLabel">
                <div class="offcanvas-header text-white border-bottom">
                    <h5 class="offcanvas-title" id="offcanvasNavbarDarkLabel">UndrWorld</h5>
                    <button type="button" class="btn-close btn-close-white shadow-none" data-bs-dismiss="offcanvas"
                        aria-label="Close"></button>
                </div>
                <!--SIder body-->
                <div class="offcanvas-body d-flex flex-column p-4">
                    <ul class="navbar-nav justify-content-center align-items-center flex-grow-1 pe-3">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'uwapp:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'uwapp:account' %}">Account</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'uwapp:category' %}">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'uwapp:product' %}">All Products</a>
                        </li>
                    </ul>
                    <!--Log in / Signup-->
                    <div class="d-flex flex-column justify-content-center align-items-center gap-3">
                        <a href="{% url 'userauth:login'  %}">Login</a>
                        <a href="{% url 'userauth:signup' %}" class="btn btn-primary">Signup</a>
                    </div>
                </div>
            </div>
        </nav>
    </section>

    <!--order_content-->

    <section style="height: 100vh;">
        <div class="container mt-5">
            <div class="row">
                <div class="col-lg-3">
                    <!-- Sidebar -->
                    <div class="list-group">
                        <a href="#" class="list-group-item list-group-item-action active">My Account</a>
                        <a href="{% url 'uwapp:account' %}" class="list-group-item list-group-item-action">Profile</a>
                        <a href="{% url 'uwapp:orders' %}" class="list-group-item list-group-item-action">Orders</a>
                        <a href="{% url 'userauth:signout' %}" class="list-group-item list-group-item-action">Logout</a>
                    </div>
                </div>
                <div class="col-lg-9">
                    <h1 class="mb-4">Your Order History</h1>
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Order ID</th>
                                    <th>Date</th>
                                    <th>Total Amount</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% if orders %}
                                {% for order in orders %}
                                <tr>
                                    <td>{{ order.id }}</td>
                                    <td>{{ order.order_date }}</td>
                                    <td>Rs.{{ order.price }}</td>
                                    <td>{{ order.product_status }}</td>
                                </tr>
                                {% endfor %}
                            {% else %}
                                <tr>
                                    <td colspan="4">No orders found.</td>
                                </tr>
                            {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        </main>
    </section>
</body>
<footer class="footer_x ">

    <div class="text-center p-3" style="background-color: white;">
        &copy; 2023 Your Website. All rights reserved.
    </div>
</footer>

</html>

{% endblock content %}