UWprj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("uwapp.urls")),
    path("user/",include("userauth.urls")),

    path("ckeditor/",include("ckeditor_uploader.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

userauth/urls.py
from django.urls import path
from userauth import views

app_name= "userauth"

urlpatterns = [
    path("signup/", views.signup,name="signup"),
    path("login/", views.signin,name="login"),
    path("logout/", views.signout,name="signout"),
]

uwapp/urls.py
from django.urls import path,include
from uwapp.views import payment_completed,payment_failed,product,login_required,cart,category,category_product,checkout,delete_item_from_cart,details,index,account,add_to_cart,orders

app_name="uwapp"

urlpatterns = [
    path("",index,name="index"),

    path("product/",product,name="product"),

    path("category/<cid>",category_product,name="category_product"),

    path("category/",category,name="category"),

    path("details/<Pid>/",details,name="details"),

    path("add_to_cart/",add_to_cart,name="add_to_cart"),

    path("cart/",cart,name="cart"),

    path("delete-from-cart/",delete_item_from_cart,name="delete-from-cart"),

    path("account/",account,name="account"),

    path("orders/",orders,name="orders"),
    
    path("checkout/",checkout,name="checkout"),


    path('payment/success/', payment_completed, name='payment_success'),
    
    path('payment/failed/', payment_failed, name='payment_failed'),

]

templates/core/async/cart-list.html
<main id="cart-list">
<body>
    {% load static %}

    <script>
        AOS.init({ once: true, });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
        <section class="taskbar ">
            <nav class="menu"  data-aos="flip-left" data-aos-duration="2000">
                <a href="{% url 'uwapp:index' %}"><img src="{% static 'img/undrwrld final logo-03.png' %}" alt="">
                </a>
            </nav>
            <nav class="menu_2">
                <a href="{% url 'userauth:login'  %}">Login</a>
                <a href="#"><img src="{% static 'img/search.png' %}" alt=""></a>
                <a href="{% url 'uwapp:cart' %}"><img src="{% static 'img/cart.png' %}" alt=""></a>
                <a href="{% url 'uwapp:account' %}"><img src="{% static 'img/user.png' %}" alt=""></a>
                <!-- Toogle -->
    
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbarDark" aria-controls="offcanvasNavbarDark">
                    <img src="{% static 'img/menu.png' %}" alt="">
                </button>
    
                <!--sider-->
                <div class="sidebar offcanvas offcanvas-end text-white" tabindex="-1" id="offcanvasNavbarDark"
                    aria-labelledby="offcanvasNavbarDarkLabel">
                    <div class="offcanvas-header text-white border-bottom">
                        <h5 class="offcanvas-title" id="offcanvasNavbarDarkLabel">UndrWorld</h5>
                        <button type="button" class="btn-close btn-close-white shadow-none" data-bs-dismiss="offcanvas"
                            aria-label="Close"></button>
                    </div>
                    <!--SIder body-->
                    <div class="offcanvas-body d-flex flex-column p-4">
                        <ul class="navbar-nav justify-content-center align-items-center flex-grow-1 pe-3">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'uwapp:index' %}">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'uwapp:account' %}">Account</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'uwapp:category' %}">Category</a>
                            </li>
                        </ul>
                        <!--Log in / Signup-->
                        <div class="d-flex flex-column justify-content-center align-items-center gap-3">
                            <a href="{% url 'userauth:login'  %}">Login</a>
                            <a href="{% url 'userauth:signup' %}" class="btn btn-primary">Signup</a>
                        </div>
                    </div>
                </div>
            </nav>
        </section>

        </section><section>
            {% if messages %}
            <div class="alert-container">
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible animate-alert" role="alert">
                    <strong>{{ message }}</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
            </div>
            {% endif %}
            
        </section>
    <section class="cartbody">
        <div class="container mt-4">
            <h2>Your happy place &#128513</h2>
            <div class="row">
                <div class="col-md-8">

                    {% for product_id, item in cart_data.items %}
                    <!-- Cart Items --> 
                    <div class="cart-item">
                        <div class="row">
                            <div class="col-md-3">
                                <img src="{{ item.image }}" alt="Product 1">
                            </div>
                            <div class="col-md-6">
                                <h4>{{ item.name }}</h4>
                                <p>{{ item.size }}<p>
                                <button class="btn btn-danger btn-sm delete-product" data-product="{{ product_id }}" >Delete</button>
                            </div>
                            <div class="col-md-3">
                                
                                <p><strong>Quantity:</strong> {{ item.qty }} * {{ item.price }}</p>
                                <p><strong>Price:</strong> Rs.{% widthratio item.price 1 item.qty  %}</p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
        
                    <script>

                        $(document).ready(function () {
                            $(".delete-product").on("click", function () {
                                let product_id = $(this).attr("data-product");
                                let this_val = $(this);
                        
                                console.log("Product_id:", product_id);
                        
                                $.ajax({
                                    url: "/delete-from-cart",
                                    data: {
                                        "id": product_id
                                    },
                                    dataType: "json",
                                    beforeSend: function () {
                                        this_val.hide(); // Corrected to hide the element
                                    },
                                    success: function (response) {
                                        this_val.show()
                                        $(".cart-items-count").text(response.totalcartitems)
                                        $("#cart-list").html(response.data)

                                    },
                                    error: function (xhr, status, error) {
                                        console.error("AJAX Error:", error);
                                    }
                                });
                            });
                        });
                        
                         
                    
                    </script>
        
                </div>
                <div class="col-md-4">
                    <!-- Cart Summary -->
                    <div class="cart-summary">
                        
                        <h4>Order Summary</h4>
                        <p>Total Items: {{ totalcartitems }}</p>
                        <p class="cart-total">Total Price: {{ cart_total_amount|floatformat:2 }}  </p>
                        <div class="cart-btn" >
                            <a href="{% url 'uwapp:product' %}" class="btn btn-primary" style="letter-spacing: 0px;">Continue Shopping</a>
                            {% if totalcartitems %}
                            <a href="{% url 'uwapp:checkout' %}"><button class="btn btn-success" style="letter-spacing: 0px;">Checkout</button></a>
                            {% endif %}
                        </div>
                    </div>
                </div>


            </div>
        </div>
        
    </section>
</body>
<footer class="footer_x ">

    <div class="text-center p-3" style="background-color: white;">
        &copy; 2023 Your Website. All rights reserved.
    </div>
</footer>
</main>
</html>